codecov:
  token: 4a3996bd-c91a-4f1d-a99e-3db2b79c0597

coverage:
  status:
    project:
      default:
        target: 65%
        threshold: null
        if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success

