coverage:
  status:
    project:
      default:
        target: 30%
        threshold: null
        if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success

ignore:
  - "weevent-jmeter/**/*"  # ignore folders and all its contents
  - "weevent-jmeter/src/main/java/com/webank/weevent/jmeter/consumer/WeEventConsumer.java"  # ignore file
  - "weevent-jmeter/src/main/java/com/webank/weevent/jmeter/producer/WeEventProducer.java"  # ignore file

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches: null

