codecov:
  token: $CODECOV_TOKEN

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: null
        if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success

