language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - py.test
  - coverage run --source=cobra -m pytest
after_success:
  - coveralls