[cryptoMaterial]
# certPath = "conf"
# CA cert file path
caCert = "ca.crt"
# SSL cert file path
sslCert = "sdk.crt"
# SSL key file path
sslKey = "sdk.key"
# enSslCert = "conf/gm/gmensdk.crt"
# enSslKey = "conf/gm/gmensdk.key"

[network]
# The peer list to connect
peers=["127.0.0.1:20200", "127.0.0.1:20201"]

# Configure a "need verify AMOP topic" as a topic message sender.
[[amop]]
# topicName = "t1"
# Public keys of the nodes that you want to send AMOP message of this topic to.
publicKeys = [ "conf/consumer_public_key_1.pem" ]

# Configure a "need verify AMOP topic" as a topic subscriber.
[[amop]]
# topicName = "t2"
# Your private key that used to subscriber verification.
privateKey = "conf/consumer_private_key.p12"
# password = "123456"

[account]
# The directory where the account private key file is placed in
keyStoreDir = "account"
# The account file path(Default load account from keyStoreDir directory when accountFilePath is not configured)
# accountFilePath = ""
# The storage format of the account, support pem and p12, default is pem
accountFileFormat = "pem"
# The address of the account used to send transactions
# When it's empty, use a randomly generated account to send transactions,
# and the randomly generated account information is stored in tmp sub-directory of keyStoreDir
# accountAddress = ""
# The password used to load the account private key file
# password = ""

[threadPool]
# The size of the thread pool used to process the callback of the channel
# Default is the number of cpu cores of the physical machine
# channelProcessorThreadSize = "16"
# The size of the thread pool used to process the transaction receipt notification
# Default is the number of cpu cores of the physical machine
# receiptProcessorThreadSize = "16"
# The max blocking queue size of the thread pool
maxBlockingQueueSize = "102400"

