server:
  port: 8082
spring:
  # datasource
  datasource:
    url: jdbc:mysql://192.168.58.138:3306/governance?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: fisco
    password: zjy2019
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 'x'
  mail: 
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 284617893@qq.com
    password: zjy621138
    from: 284617893@qq.com
  pid:
    fail-on-write-error: true
    file: ./logs/governance.pid
http: 
  client: 
    max-total: 200
    max-per-route: 500
    connection-request-timeout: 3000
    connection-timeout: 3000
    socket-timeout: 5000
logging:
  config: classpath:log4j2.xml