server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/governance?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: xxxx
    password: yyyy
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 'x'
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: mailusername@163.com
    password: mailpwd
  pid:
    fail-on-write-error: true
    file: ./logs/governance.pid
http:
  client:
    max-total: 200
    max-per-route: 500
    connection-request-timeout: 3000
    connection-timeout: 3000
    socket-timeout: 5000
https: 
  read-timeout: 3000
  connect-timeout: 3000
logging:
  config: classpath:log4j2.xml