server: 
  servlet: 
    context-path: /weevent-governance
  ssl: 
    enabled: false
    key-store: classpath:server.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: weevent  
    
spring:
  profiles:
    active: dev
  http: 
    encoding: 
      charset: UTF-8
      force: true
  mvc:
    static-path-pattern: /** 
    throw-exception-if-no-handler-found: true
  resources:
    static-locations: classpath:/
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.webank.weevent.governance.mapper
