CREATE TABLE t_account (
	id INTEGER generated BY DEFAULT AS identity,
	create_date TIMESTAMP,
	last_update TIMESTAMP,
	delete_at BIGINT NOT NULL,
	email VARCHAR (255),
	PASSWORD VARCHAR (255),
	username VARCHAR (255),
	PRIMARY KEY (id)
);
 CREATE TABLE t_broker (
	id INTEGER generated BY DEFAULT AS identity,
	create_date TIMESTAMP,
	last_update TIMESTAMP,
	broker_url VARCHAR (64),
	delete_at BIGINT NOT NULL,
	NAME VARCHAR (255),
	user_id INTEGER CHECK (user_id >= 1),
	webase_url VARCHAR (255),
	PRIMARY KEY (id)
);
 CREATE TABLE t_permission (
	id INTEGER generated BY DEFAULT AS identity,
	create_date TIMESTAMP,
	last_update TIMESTAMP,
	broker_id INTEGER,
	user_id INTEGER,
	PRIMARY KEY (id)
);
 CREATE TABLE t_rule_database (
	id INTEGER generated BY DEFAULT AS identity,
	create_date TIMESTAMP,
	last_update TIMESTAMP,
	broker_id INTEGER,
    database_url VARCHAR (255),
	datasource_name VARCHAR (255),
	optional_parameter VARCHAR (256),
	PASSWORD VARCHAR (255),
	system_tag BOOLEAN,
	table_name VARCHAR (255),
	user_id INTEGER,
	username VARCHAR (255),
	PRIMARY KEY (id)
);
 CREATE TABLE t_rule_engine (
	id INTEGER generated BY DEFAULT AS identity,
	create_date TIMESTAMP,
	last_update TIMESTAMP,
	broker_id INTEGER,
	cep_id VARCHAR (255),
	condition_field VARCHAR (255),
	condition_type INTEGER,
	delete_at BIGINT NOT NULL,
	error_destination VARCHAR (255),
	from_destination VARCHAR (255),
	group_id VARCHAR (255),
	payload VARCHAR (255),
	payload_type INTEGER,
	rule_database_id INTEGER,
	rule_name VARCHAR (128),
	select_field VARCHAR (255),
	STATUS INTEGER,
	system_tag BOOLEAN,
	to_destination VARCHAR (255),
	user_id INTEGER,
	brokerUrl VARCHAR (255),
	PRIMARY KEY (id)
);
 CREATE TABLE t_rule_engine_condition (
	id INTEGER generated BY DEFAULT AS identity,
	create_date TIMESTAMP,
	last_update TIMESTAMP,
	rule_id INTEGER,
	sql_condition_json VARCHAR (255),
	PRIMARY KEY (id)
);
 CREATE TABLE t_topic (
	id INTEGER generated BY DEFAULT AS identity,
	create_date TIMESTAMP,
	last_update TIMESTAMP,
	broker_id INTEGER,
	creater VARCHAR (255),
	delete_at BIGINT NOT NULL,
	description VARCHAR (255),
	group_id VARCHAR (64),
	topic_name VARCHAR (128),
	PRIMARY KEY (id)
);
 CREATE TABLE t_topic_historical (
	id INTEGER generated BY DEFAULT AS identity,
	create_date TIMESTAMP,
	last_update TIMESTAMP,
	brokerId INTEGER,
	eventId VARCHAR (64),
	groupId VARCHAR (64),
	topicName VARCHAR (128),
	PRIMARY KEY (id)
);

 ALTER TABLE t_broker ADD CONSTRAINT brokerUrlDeleteAt UNIQUE (broker_url, delete_at) ;
 ALTER TABLE t_rule_engine ADD CONSTRAINT ruleNameDeleteAt UNIQUE (rule_name, delete_at);
 ALTER TABLE t_topic ADD CONSTRAINT topicNameBrokerGroupDelete UNIQUE (topic_name,broker_id,group_id,delete_at);
 ALTER TABLE t_topic_historical ADD CONSTRAINT brokerIdGroupIdEventId UNIQUE (brokerId, groupId, eventId);